# Generated by Django 2.2.17 on 2021-03-27 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=128)),
                ('competitionDescription', models.CharField(default=None, max_length=200)),
                ('competitionID', models.CharField(max_length=8)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('userID', models.CharField(max_length=8, unique=True)),
                ('password', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images/')),
                ('participations', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('luckyDrawWinner', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('userID', models.CharField(max_length=8, unique=True)),
                ('password', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images/')),
                ('competitionsCreated', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designImage', models.ImageField(upload_to='Submission_images/')),
                ('submissionDescription', models.CharField(default=None, max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('winner', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='designmytee.Competition')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='designmytee.Designer')),
            ],
        ),
    ]
