# Generated by Django 2.2.17 on 2021-04-01 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designmytee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=128)),
                ('lastName', models.CharField(max_length=128)),
                ('contactNumber', models.CharField(max_length=11)),
                ('contactEmail', models.CharField(max_length=200)),
                ('suggestionsOrFeedback', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='competitionID',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='userID',
        ),
        migrations.AddField(
            model_name='competition',
            name='competitionImage',
            field=models.ImageField(blank=True, upload_to='competition_images/'),
        ),
        migrations.AddField(
            model_name='designer',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='designer',
            name='participations',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='designer',
            name='wins',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designmytee.Designer'),
        ),
    ]
