# Generated by Django 2.2.17 on 2021-03-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='competitionsCreated',
            field=models.IntegerField(default=False),
        ),
    ]
