# Generated by Django 2.2.17 on 2021-04-05 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designmytee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.CreateModel(
            name='Support_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=128)),
                ('lastName', models.CharField(max_length=128)),
                ('contactNumber', models.CharField(max_length=11)),
                ('contactEmail', models.EmailField(max_length=200)),
                ('suggestionsOrFeedback', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name_plural': 'competitions'},
        ),
        migrations.RemoveField(
            model_name='competition',
            name='competitionID',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='luckyDrawWinner',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='userID',
        ),
        migrations.AddField(
            model_name='competition',
            name='competitionImage',
            field=models.ImageField(blank=True, upload_to='competition_images/'),
        ),
        migrations.AddField(
            model_name='competition',
            name='competitionWinner',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_Winner', to='designmytee.Submission'),
        ),
        migrations.AddField(
            model_name='competition',
            name='expiryDate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='competition',
            name='luckyDrawWinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competition',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='designer',
            name='participations',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='designer',
            name='picture',
            field=models.ImageField(blank=True, default='images/homepage-cover.jpeg', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='designer',
            name='wins',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='competition',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='designmytee.Competition'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='designImage',
            field=models.ImageField(blank=True, null=True, upload_to='Submission_images/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='designmytee.Submission'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
