# Generated by Django 2.2.17 on 2021-04-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0002_auto_20210403_0051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name_plural': 'competitions'},
        ),
        migrations.AddField(
            model_name='competition',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
