# Generated by Django 2.2.17 on 2021-03-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0002_auto_20210322_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='host',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='designImage',
            field=models.ImageField(upload_to='Submission_images/'),
        ),
    ]
