# Generated by Django 2.2.17 on 2021-04-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0003_auto_20210403_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
