# Generated by Django 2.2.17 on 2021-03-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0004_submission_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='name',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competitionID',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
