# Generated by Django 2.2.17 on 2021-04-02 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0004_auto_20210403_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='luckyDrawWinner',
        ),
        migrations.AddField(
            model_name='competition',
            name='competitionWinner',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_Winner', to='designmytee.Submission'),
        ),
        migrations.AddField(
            model_name='competition',
            name='expiryDate',
            field=models.DateField(default=None),
        ),
    ]
