# Generated by Django 2.2.17 on 2021-03-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0005_auto_20210323_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='name',
            new_name='CompetitionName',
        ),
    ]
