# Generated by Django 2.2.17 on 2021-04-04 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0005_auto_20210404_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
