# Generated by Django 2.2.17 on 2021-04-04 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designmytee', '0006_auto_20210404_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='luckyDrawWinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
