# Generated by Django 2.2.17 on 2021-03-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0006_auto_20210323_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='CompetitionName',
            field=models.CharField(max_length=128),
        ),
    ]
