# Generated by Django 2.2.17 on 2021-03-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0007_auto_20210323_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='competition',
        ),
    ]
