# Generated by Django 2.2.17 on 2021-03-23 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0008_remove_submission_competition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='CompetitionName',
        ),
        migrations.AddField(
            model_name='competition',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='competition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='designmytee.Competition'),
        ),
    ]
