# Generated by Django 2.2.17 on 2021-03-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0010_remove_competition_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competitionID',
            field=models.CharField(max_length=8),
        ),
    ]
