# Generated by Django 2.2.17 on 2021-03-23 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0011_auto_20210323_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designmytee.Competition'),
        ),
    ]
