# Generated by Django 2.2.17 on 2021-03-23 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0013_remove_submission_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='competition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='designmytee.Competition'),
        ),
    ]
