# Generated by Django 2.2.17 on 2021-03-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0014_submission_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='title',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
