# Generated by Django 2.2.17 on 2021-03-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0015_competition_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='competitionDescription',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='submission',
            name='submissionDescription',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
