# Generated by Django 2.2.17 on 2021-03-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0016_auto_20210323_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='competitionImage',
            field=models.ImageField(blank=True, upload_to='competition_images'),
        ),
    ]
