# Generated by Django 2.2.17 on 2021-03-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0017_competition_competitionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competitionImage',
            field=models.ImageField(blank=True, upload_to='competition_images/'),
        ),
    ]
