# Generated by Django 2.2.17 on 2021-03-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0018_auto_20210327_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supportID', models.CharField(max_length=8)),
                ('firstName', models.CharField(max_length=128)),
                ('lastName', models.CharField(max_length=128)),
                ('contactNumber', models.CharField(max_length=11)),
                ('contactEmail', models.CharField(max_length=200)),
                ('suggestionsOrFeedback', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='designer',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
