# Generated by Django 2.2.17 on 2021-03-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0019_auto_20210329_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competitionID',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='support_request',
            name='supportID',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
