# Generated by Django 2.2.17 on 2021-03-31 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designmytee', '0002_competition_competitionimage'),
        ('designmytee', '0020_auto_20210329_2051'),
    ]

    operations = [
    ]
